version: "3.9"
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "finwave"
      POSTGRES_USER: "finwave"
      POSTGRES_PASSWORD: "change_me"
    ports:
      - "5432:5432"
